- name: remove packages for install demo
  hosts: ubuntu
  become: true
  tasks:
    - apt:
        name:
        # each command individually:
        - inetutils-telnet
        - inetutils-ping
        - inetutils-traceroute
        #
        - bat
        - ripgrep
        - silversearcher-ag
        #
        # already installed:
        - lsd # can point out that this was already installed
        - git-delta

- name: remove packages for install demo
  hosts: arch
  become: true
  tasks:
    - pacman:
        name:
        - inetutils
        - bat
        - ripgrep
        - the_silver_searcher
        #
        # already installed:
        - lsd
        - git-delta

      # TODO ollama demos
      # - name: Install Ollama
      #   become: true
      #   apt:
      #       name: ollama
      #       state: present
      #
      #        run `ollama` in ubuntu => tells you what to install
      #        sudo snap install ollama
      #        # confirm this is wise
