# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/refs/heads/main/src/ansiblelint/schemas/playbook.json

- name: Ubuntu setup
  hosts: ubuntu
  become: true
  tasks:
    - name: Install Packages
      apt:
        name:
          # each command individually:
          - inetutils-telnet
          - inetutils-ping
          - inetutils-traceroute
          #
          - bat
          - ripgrep
          - silversearcher-ag
          #
          # already installed:
          - lsd # can point out that this was already installed
          - git-delta

- name: Arch setup
  hosts: arch
  become: true
  tasks:
    - name: Install Packages
      pacman:
        name:
          - inetutils
          - bat
          - ripgrep
          - the_silver_searcher
          #
          # already installed:
          - lsd
          - git-delta
