
- name: Install valkey
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install valkey on Arch
      when: ansible_facts["os_family"] == "Archlinux"
      tags: install1,arch
      community.general.pacman:
        name: valkey
        state: present
        update_cache: true

    - name: Install valkey on Ubuntu
      when: ansible_facts["os_family"] == "Debian"
      tags: install2,ubuntu
      ansible.builtin.apt:
        name: valkey-server
        state: present
        update_cache: true

- name: Ensure valkey is running
  hosts: all
  become: true
  tags: running
  gather_facts: true

  tasks:
    - name: Enable and start valkey
      ansible.builtin.systemd:
        name: valkey
        enabled: true
        state: starte
