- name: Install valkey
  hosts: all
  become: true

  tasks:
    - name: Install valkey on Arch
      when: ansible_facts["os_family"] == "Archlinux"
      tags: install1, arch
      community.general.pacman:
        name: valkey
        state: present
        update_cache: true

    - name: Install valkey on Ubuntu
      when: ansible_facts["distribution"] == "Ubuntu"
      tags: install2, ubuntu
      ansible.builtin.apt:
        name: valkey-server
        state: present
        update_cache: true

- name: Ensure valkey is running
  hosts: all
  become: true
  tags: running

  vars:
    service_name:
      Archlinux: valkey
      Ubuntu: valkey-server

  tasks:
    - name: Enable and start valkey
      ansible.builtin.systemd:
        name: '{{ service_name[ansible_facts["distribution"]] }}'
        enabled: true
        state: started

