- name: Ensure users can login
  become: true
  hosts: arch1,arch2
  tasks:
    - name: Ensure wes user
      ansible.builtin.user:
        name: wes
        # shell: /usr/bin/fish
        # openssl passwd -6 -noverify # type password and generate hash
        # password: $6$wln4Y7nDCfN5j7Qe$xUPqq8uc/ogde.IPuEtPJ7PffC3KYKrD/WOyEZ9KYmPpzvTQPCzoKLnLDnY7XQgoLXLIOD4ujfAR8pl/tNnOx0
    - name: Database service account
      ansible.builtin.user:
        name: db_sa
        state: absent

- name: Setup dotfiles for wes user
  hosts: arch1
  become: true
  tags: dotfiles
  tasks:
    - name: Clone dotfiles
      ansible.builtin.git:
        repo: 'https://github.com/g0t4/dotfiles.git'
        dest: /home/wes/repos/github/g0t4/dotfiles

    - name: create fish config directory
      ansible.builtin.file:
        state: directory
        path: /home/wes/.config/fish/
        owner: wes
        group: wes

    - name: symlink config.fish
      ansible.builtin.file:
        state: link
        src: /home/wes/repos/github/g0t4/dotfiles/fish/config/config.fish
        dest: /home/wes/.config/fish/config.fish
        owner: wes
        group: wes








- name: ssh access
  hosts: arch1
  tags: ssh
  tasks:
    - name: Create user's ssh directory
      become: true
      ansible.builtin.file:
        state: directory
        dest: /home/wes/.ssh
        owner: wes
        group: wes
    - name: create ~/.ssh/authorized_keys
      become: true
      ansible.builtin.copy:
        src: authorized_keys
        dest: /home/wes/.ssh/
        owner: wes
        group: wes









