- name: Ensure users can login
  become: true
  hosts: arch1,arch2
  tasks:
    - name: Ensure wes user
      ansible.builtin.user:
        name: wes
        # password: encrypted_value
        # shell: /usr/bin/fish
    - name: Ensure database service account
      ansible.builtin.user:
        name: db_sa
        state: absent

- name: Setup dotfiles
  hosts: arch1
  tags: dotfiles
  become: true
  become_user: wes
  tasks:
    - name: Clone repo
      ansible.builtin.git:
        repo: https://github.com/g0t4/dotfiles
        dest: ~/repos/github/g0t4/dotfiles
        version: master
        update: true
    - ansible.builtin.file:
        path: ~/.config/fish
        state: directory
    - ansible.builtin.file:
        src: ~/repos/github/g0t4/dotfiles/fish/config/config.fish
        dest: ~/.config/fish/config.fish
        state: link
        force: true


- name: ssh access
  hosts: arch1
  tags: ssh
  become: true
  tasks:
    - name: Create user's ssh directory
      ansible.builtin.file:
        state: directory
        dest: /home/wes/.ssh
        owner: wes
        group: wes
        mode: "0700"
    - name: Create ~/.ssh/authorized_keys
      ansible.builtin.copy:
        src: authorized_keys
        dest: /home/wes/.ssh/
        owner: wes
        group: wes
        mode: "0600"
