- name: Ensure users can login
  become: true
  hosts: arch1,arch2
  tasks:
    - name: Ensure wes user
      ansible.builtin.user:
        name: wes
        # shell: /usr/bin/fish
        # openssl passwd -6 -noverify # type password and generate hash
        # password: $6$wln4Y7nDCfN5j7Qe$xUPqq8uc/ogde.IPuEtPJ7PffC3KYKrD/WOyEZ9KYmPpzvTQPCzoKLnLDnY7XQgoLXLIOD4ujfAR8pl/tNnOx0
    - name: Database service account
      ansible.builtin.user:
        name: db_sa
        state: absent

- name: Setup dotfiles
  hosts: arch1
  tags: dotfiles
  tasks:
    - name: Clone repo
      ansible.builtin.git:
        repo: 'https://github.com/ansible/ansible.git'







