# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
    config.vm.box = 'wesdemos/arch-arm'
    config.vm.box_check_update = false

    (1..3).each do |number|
        name = "arch#{number}"

        config.vm.define name do |node|
            node.vm.network 'public_network', ip: "192.168.6.10#{number}", netmask: '21'
            node.vm.network 'forwarded_port', id: 'ssh', host: "810#{number}", guest: '22'
            node.vm.hostname = name

            # packages - skip for m1 demo of failing pacman install
            # node.vm.provision 'shell', name: 'packages', inline: 'pacman -Sy --noconfirm lsd fd', privileged: true # TODO add lsd to vagrant box
        end
    end

    (1..3).each do |number|
        name = "ubuntu#{number}"
        config.vm.define name do |node|
            node.vm.box = 'wesdemos/ubuntu2604-arm'
            node.vm.network 'public_network', ip: "192.168.6.11#{number}", netmask: '21'
            node.vm.network 'forwarded_port', id: 'ssh', host: "811#{number}", guest: '22'
            node.vm.hostname = name

            # disable /vagrant shared folder, broken for just ubuntu2604 and not needed
            node.vm.synced_folder '.', '/vagrant', disabled: true

            # packages
            node.vm.provision 'shell', name: 'packages', inline: 'apt-get update && apt-get install -y lsd fd-find ripgrep', privileged: true
        end
    end

    config.vm.provision 'shell', path: './bootstrap/dotfiles.fish', privileged: false

    config.vm.provider 'parallels' do |vb|
        # nest inside loops above for targeting specific nodes
        vb.memory = '8192'
        vb.cpus = 4
    end

end
