- name: Setup MOTD
  hosts: all
  tasks:
    - name: nuke hushlogin for vagrant user
      ansible.builtin.file:
        dest: /home/vagrant/.hushlogin
        state: absent
    - name: Deploy MOTD
      become: true
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/motd
