# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "wesdemos/arch-arm"
    config.vm.box_check_update = false

    (1..3).each do |number|
        name = "arch#{number}"

        config.vm.define name do |node|
            node.vm.network 'public_network', ip: "192.168.6.10#{number}", netmask: "21"
            node.vm.network 'forwarded_port', id: 'ssh', host: "810#{number}", guest: "22"
            node.vm.hostname = name
        end
    end

    (1..3).each do |number|
        name = "ubuntu#{number}"
        config.vm.define name do |node|
            node.vm.box = "wesdemos/ubuntu2604-arm"
            node.vm.network 'public_network', ip: "192.168.6.11#{number}", netmask: "21"
            node.vm.network 'forwarded_port', id: 'ssh', host: "811#{number}", guest: "22"
            node.vm.hostname = name

            # ubuntu.vm.provision "shell", inline: <<-SHELL
            #   sudo apt update
            #   sudo apt install node-typescript npm nodejs zsh ripgrep
            # SHELL
        end
    end

    # PRN if disk space runs out => see course-rancher Vagranfile for script to expand
    #   OR, modify packer build where it sets 20G disk...
    #   REMOVE THIS IF no issues in lab setup preparation

    config.vm.provision 'shell', path: './bootstrap/dotfiles.fish', privileged: false

    # * vagrant + ansible integration
    config.vm.provision 'absent', type: 'ansible' do |ansible|
       ansible.playbook = './bootstrap/absent.yml'
    #
    #   # vagrant provision --provision-with ansible|absent # provisioner type (ansible) OR provision's instance name (absent)
    #   #
    #   # * must install ansible on host (accessible to vagrant command)
    #   #   * NOTE vagrant provides inventory to ansible commands (i.e. when it executes ansible-playbook)
    #   #     thus the inventory.yml/inventory.ini are not necessary for `vagrant provision` demos...
    #   #     but, inventory lists can be helpful to test a playbook w/o vagrant involved (often faster to run ansible-playbook directly and iterate on that though, leave `vagrant provision` as the "production" pathway)
    #   # ansible.inventory_path = './inventory.yml' # OPTIONAL configure inventory
    #   # * docs: https://developer.hashicorp.com/vagrant/docs/provisioning/ansible
    #   # * ansible provisioner src:
    #   #    options: https://github.com/hashicorp/vagrant/blob/0b7d460a/plugins/provisioners/ansible/config/base.rb#L14-L34
    #   # ansible.limit = "arch2"
    #   # ansible.raw_arguments = [ "--check", "--diff" ]
    #   # ansible.raw_arguments = [ "-vvv" ]
    #   # for packages, --diff will show name+version per pkg (+added/-removed)
    #   # ansible.extra_vars = { packages: ["inetutils"] }
    end

    config.vm.provider 'parallels' do |vb|
        # nest inside loops above for targeting specific nodes
        vb.memory = '8192'
        vb.cpus = 4
    end

end
